apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapi
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: webapi
          image: flippercoin/webapi:20190118
          ports:
            - containerPort: 8080
          imagePullPolicy: Never